name: "Handle push to master"

on:
  push:
    branches: [master]

jobs:
  tests:
    strategy:
      matrix:
        ghc: [ghc984, ghc9102, ghc9122]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # Build and run
      - name: Build tests runner
        run: nix build .#packages.x86_64-linux.${{ matrix.ghc }}.webcolor-labels

  handle-push-to-master:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build webcolor-labels-dist
        run: nix build .#webcolor-labels-dist

      - name: Deploy webcolor-labels release candidate
        uses: haskell-actions/hackage-publish@v1
        with:
          hackageToken: ${{ secrets.HACKAGE_API_KEY }}
          packagesPath: result/packages
          docsPath: result/docs
          publish: false
